apiVersion: v1
kind: Template
labels:
  app: mocks
  template: mocks
metadata:
  name: mocks

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mocks
    name: mocks
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        name: mocks
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: mocks
          name: mocks
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mocks
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mocks
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: mocks
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
          env:
          - name: KEYCLOAK_CLIENT_BASE_URL
            value: ${KEYCLOAK_CLIENT_BASE_URL}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: ${KEYCLOAK_IMAGE}:${KEYCLOAK_IMAGE_TAG}
          imagePullPolicy: Always
          name: keycloak
          env:
          - name: DB_VENDOR
            value: "h2"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30

- apiVersion: v1
  kind: Service
  metadata:
    name: mocks
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 9000
    selector:
      app: mocks
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    name: rbac
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 9000
    selector:
      app: mocks
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    name: entitlements-api-go
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 9000
    selector:
      app: mocks
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    name: keycloak
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mocks
    sessionAffinity: None
    type: ClusterIP

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: keycloak
    name: keycloak
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: keycloak
      weight: 100
    wildcardPolicy: None

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: mocks
    name: mocks
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: mocks
      weight: 100
    wildcardPolicy: None

parameters:
- name: IMAGE
  value: "quay.io/cloudservices/mocks"
- name: IMAGE_TAG
  value: "latest"
- name: KEYCLOAK_IMAGE
  value: "quay.io/keycloak/keycloak"
- name: KEYCLOAK_IMAGE_TAG
  value: "latest"
- name: REPLICAS
  description: The number of replicas to use in the deployment
  value: "1"
- name: KEYCLOAK_CLIENT_BASE_URL
  description: The base url to use for a redirect URI when configuring keycloak client
  value: "https://front-end-aggregator"
