apiVersion: v1
kind: Template
labels:
  app: rbac
  template: rbac
metadata:
  name: mock-rbac

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: rbac
    name: rbac
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        name: rbac
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: rbac
          name: rbac
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rbac
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rbac
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - command:
          - /bin/bash
          - -c
          - ./run.sh rbac
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: rbac
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 75m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30

- apiVersion: v1
  kind: Service
  metadata:
    name: rbac
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: rbac
    sessionAffinity: None
    type: ClusterIP

parameters:
- name: IMAGE
  value: "quay.io/cloudservices/mocks"
- name: IMAGE_TAG
  value: "latest"
- name: REPLICAS
  description: The number of replicas to use in the deployment
  value: "1"
